version: '3.8'
services:

  # Application
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    restart: unless-stopped
    extra_hosts:
    - "host.docker.internal:host-gateway"
    depends_on:
      - "database"

  # Web Server
  web:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - "app"
    ports:
      - 80:80

  # Database
  database:
    image: mysql:5.7.35
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 33063:3306

volumes:
  dbdata:
